# H1 TITLE
## H2 TITLE

In [1]:
print("Buy the dip ?")

Buy the dip ?


# Exercise 1: 
## Your first NumPy array

In [2]:
import numpy as np


my_np_array = np.array([
    42,                          # integer
    3.14,                        # float
    "hello",                     # string
    {"key": "value"},            # dictionary
    [1, 2, 3],                   # list
    (4, 5, 6),                   # tuple
    {7, 8, 9},                   # set
    True                         # boolean
], dtype=object)

for i in my_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


# Exercise 2: 
## Zeros

In [3]:
import numpy as np

zeros_array = np.zeros(300, dtype=int)

In [4]:
print(zeros_array)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]


## Reshape

In [5]:
reshaped_array = zeros_array.reshape(3, 100)

In [6]:
print (reshaped_array)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


# Exercise 3: 
## Slicing

### 1 ~ 100

In [7]:
import numpy as np

In [8]:
numbers = np.arange (1, 101, dtype=int)

In [9]:
print (numbers)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


### Odd integers

In [10]:
odd_numbers = numbers[numbers % 2 != 0]

In [11]:
print (odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### Even Reverse

In [12]:
even_numbers = numbers[numbers % 2 == 0]

In [13]:
even_numbers_reversed = np.flip(even_numbers)

In [14]:
print (even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Q1 modified 

In [15]:
numbers_q1_modified = numbers.copy()

In [16]:
numbers_q1_modified[1::3] = 0

In [17]:
print (numbers_q1_modified)

[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


## Exercise 4
### Random

### Random Generator

In [22]:
import numpy as np

In [23]:
np.random.seed(888)

In [24]:
normal_1d = np.random.randn(100)

In [25]:
print(normal_1d)

[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762e-01
 -1.40481067e+00 -6.54547

In [26]:
rand_8x8 = np.random.randint(1, 11, size=(8, 8))

In [27]:
print(rand_8x8)

[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]


In [28]:
rand_4_2_5 = np.random.randint(1, 18, size=(4, 2, 5))

In [29]:
print(rand_4_2_5)

[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


## Exercise 5: 
### Split, concatenate, reshape arrays

In [42]:
import numpy as np

In [43]:
array1 = np.arange (1, 51, dtype=int)

In [44]:
print (array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [45]:
array2 = np.arange (51, 101, dtype=int)


In [47]:
print (array2)

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [48]:
full_array = np.concatenate ((array1, array2))

In [49]:
print (full_array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [50]:
reshaped = full_array.reshape(10, 10)

In [51]:
print (reshaped)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


## Exercise 6: 
### Broadcasting and Slicing

In [59]:
import numpy as np

In [60]:
arr = np.ones((9, 9), dtype=np.int8)

In [61]:
print(arr)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [62]:
arr[1:-1, 1:-1] = 0
arr[2:-2, 2:-2] = 1
arr[3:-3, 3:-3] = 0
arr[4, 4] = 1

In [63]:
print(arr)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [64]:
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)
result = array_1.reshape(-1, 1) * array_2

In [65]:
print(result)

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


### Exercise 7: 
## NaN


In [66]:
import numpy as np

In [67]:
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))

In [68]:
grades[[1, 2, 5, 7], 0] = np.nan

In [71]:
print("Grades array (columns: Exam 1, Exam 2):")

Grades array (columns: Exam 1, Exam 2):


In [72]:
print(grades)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]


In [73]:
third_col = np.where(~np.isnan(grades[:, 0]), grades[:, 0], grades[:, 1])

In [74]:
print ( third_col)

[7. 2. 8. 9. 8. 2. 8. 6. 9. 8.]


In [75]:
grades_with_third = np.column_stack((grades, third_col))

In [76]:
print(grades_with_third)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


## Exercise 8

### Wine

In [86]:
import numpy as np

In [88]:
data = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header=1, dtype=np.float32)

In [89]:
optimized_size = data.nbytes

In [90]:
if optimized_size <= 76800:
    print("Data optimized successfully.")
else:
    print("Optimization criteria not met.")

Data optimized successfully.


In [91]:
rows = data[[1, 6, 11]]
rows = rows[~np.isnan(rows).any(axis=1)]
print("Selected rows:\n", rows)

Selected rows:
 [[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]


In [92]:
np.set_printoptions(suppress=True)

In [93]:
print(rows)

[[  7.8      0.88     0.       2.6      0.098   25.      67.       0.9968
    3.2      0.68     9.8      5.    ]
 [  7.9      0.6      0.06     1.6      0.069   15.      59.       0.9964
    3.3      0.46     9.4      5.    ]
 [  7.5      0.5      0.36     6.1      0.071   17.     102.       0.9978
    3.35     0.8     10.5      5.    ]]


In [94]:
has_high_alcohol = np.any(data[:, 10] > 20)

In [95]:
print("Any wine with alcohol > 20%:", has_high_alcohol) 

Any wine with alcohol > 20%: False


In [96]:
mean_alcohol = np.nanmean(data[:, 10])

In [97]:
print("Average alcohol:", round(mean_alcohol, 6))

Average alcohol: 10.422984


In [98]:
ph = data[:, 8]

In [99]:
print("25 percentile:", round(np.nanpercentile(ph, 25), 2))
print("50 percentile:", round(np.nanpercentile(ph, 50), 2))
print("75 percentile:", round(np.nanpercentile(ph, 75), 2))
print("mean:", round(np.nanmean(ph), 2))
print("min:", round(np.nanmin(ph), 2))
print("max:", round(np.nanmax(ph), 2))  

25 percentile: 3.21
50 percentile: 3.31
75 percentile: 3.4
mean: 3.31
min: 2.74
max: 4.01


In [100]:
sulphates = data[:, 9]
quality = data[:, 11]
thresh = np.nanpercentile(sulphates, 20)
mask = sulphates < thresh
mean_quality_least_sulphate = np.nanmean(quality[mask])

In [101]:
print("Mean quality for 20% least sulphate:", round(mean_quality_least_sulphate, 1))

Mean quality for 20% least sulphate: 5.2


In [102]:
best_quality = np.nanmax(quality)
worst_quality = np.nanmin(quality)
mean_best = np.nanmean(data[quality == best_quality], axis=0)
mean_worst = np.nanmean(data[quality == worst_quality], axis=0)

In [103]:
print("Mean values for best quality wine:\n", np.round(mean_best, 6))

Mean values for best quality wine:
 [ 8.566666  0.423333  0.391111  2.577778  0.068444 13.277778 33.444443
  0.995212  3.267222  0.767778 12.094444  8.      ]


In [104]:
print("Mean values for worst quality wine:\n", np.round(mean_worst, 6))

Mean values for worst quality wine:
 [ 8.359998  0.8845    0.171     2.635     0.1225   11.       24.9
  0.997464  3.398     0.57      9.955     3.      ]


## Exercise 9: 
### Football tournament

In [111]:
import numpy as np
import itertools
from functools import reduce

In [108]:
model = np.loadtxt('model_forecasts.txt', delimiter=',')

In [109]:
model = np.nan_to_num(model, nan=0.0)

In [110]:
teams = np.arange(10)
best_score = float('inf')
best_pairing = None

In [112]:
print (teams)

[0 1 2 3 4 5 6 7 8 9]


In [113]:
def calc_score(perm):
    pairs = [(perm[i], perm[i+1]) for i in range(0, 10, 2)]
    return sum(model[t1, t2]**2 for t1, t2 in pairs), perm

In [117]:
perm_scores = map(calc_score, itertools.permutations(teams))

In [119]:
best_pairs = [(best_perm[i], best_perm[i+1]) for i in range(0, 10, 2)]
output = np.array([[pair[0] for pair in best_pairs],
                   [pair[1] for pair in best_pairs]])

In [120]:
print("Optimal tournament pairing:")
print(output)
print(f"Minimum sum of squared differences: {best_score}")

Optimal tournament pairing:
[[0 1 2 3 5]
 [8 7 9 4 6]]
Minimum sum of squared differences: 2.9242
